docs/output-formats/html-basics.qmd

mirrors the later examples specifying css in YAML.

use styles.css filename as initial css example

---

docs/websites/website-navigation.qmd

Currently the link on the 404 pages sections is https://quarto.org/docs/websites/website-navigation.html#pages
The header is `# 404 pages` but the id has been trimmed form leading non alphabet character. 
This is because extensions [auto-identifier](https://pandoc.org/MANUAL.html#extension-auto_identifiers) will 
> Remove everything up to the first letter  (identifiers may not begin with a number or punctuation mark)
I think it would be better to have the 404 mention in the link. so I suggestion we put the 404 mention at the end of the id 
````
```` 
This is what this PR is about so that the link will become
https://quarto.org/docs/websites/website-navigation.html#pages-404
If it is not too late to change the identifier of this heading.
I understand if this idea is rejected though - it is …

Add a more precise id on the 404 page section

---

docs/authoring/language.qmd

Hi! In the website https://quarto.org/docs/authoring/language.html#translations the language subtag for Portuguese is `pr` but should be  `pt` (as it is in https://r12a.github.io/app-subtags/ and used in https://github.com/quarto-dev/quarto-cli/tree/main/src/resources/language )

Language subtag is pr in the docs, but sould be pt (for Portuguese) (fix typo)

---

docs/books/book-basics.qmd

After running `quarto create-project` this is the folder contents:
```
>ls -l
total 63
drwxr-xr-x 1 Danie Danie     0 Dec 27 00:20 _book
-rw-r--r-- 1 Danie Danie   270 Dec 27 00:16 _quarto.yml
-rw-r--r-- 1 Danie Danie   272 Dec 27 00:23 bigbookofpython.Rproj
-rw-r--r-- 1 Danie Danie 51194 Dec 27  2021 cover.png
-rw-r--r-- 1 Danie Danie   121 Dec 27 00:16 index.qmd
-rw-r--r-- 1 Danie Danie   139 Dec 27 00:16 intro.qmd
-rw-r--r-- 1 Danie Danie   436 Dec 27  2021 references.bib
-rw-r--r-- 1 Danie Danie    44 Dec 27 00:16 references.qmd
-rw-r--r-- 1 Danie Danie    60 Dec 27 00:16 summary.qmd
```
the current site makes references to `index.md`, `introduction.md`, and `summary.md`

fix potential typo for qmd files after quarto create-project

---

docs/output-formats/html-themes.qmd

Changes "code blocks" to "callouts" for description of `$callout-border-width` variable.
Pretty sure this was a mixup 🙂

Correct `$callout-border-width` description

---

docs/tools/vscode.qmd

At least in Quarto version 0.3.76 the `quarto convert` command doesn't work like this.
I fixed it to reflect the current version.

Fixed errors in VS Code docs RE `convert` cmd

---

docs/authoring/tables.qmd

I think that ending the column header with `:` may have been a typo, or it's intentional and valid. But its presentation seems to indicate that one would need to end the column header with `:` to enable the `tbl-colwidth` attribute, which is not the case.

Fix tbl-colwidths column header example

---

docs/get-started/authoring/rstudio.qmd

For the Insert Anything option to work, the user must be in Visual Editor mode.  The YAML header does not specify that mode, so when the user gets to this part of the tutorial it fails to work.

Specify "Insert Anything" requires visual editor

---

docs/computations/python.qmd

Fix the unclosed bracket for the vscode quarto extension link under the python page

Fix typo in python.qmd

---

_quarto.yml

Adds `aria-label` params to icons in the header and footer for accessibility (n.b. I did not re-render the site, as it looks like that occurs on GitHub).

Add aria-labels to icon-only menu items

---

docs/output-formats/ms-word.qmd

Is the currently shown `section-numbers` out of date? 
The syntax `number-sections` works, and is consistent with documenation here: https://quarto.org/docs/output-formats/ms-word.html#section-numbering

Update ms-word.qmd example yaml

---

docs/visual-editor/content.qmd

Fix a typo (most likely) in [`docs/visual-editor/content.qmd`](./docs/visual-editor/content.qmd) `enableEmjoi = true` instead of `enableEmoji = true`.
This is related to two (built) files in `_site`.

fix: typo `enableEmjoi`

---

docs/computations/_knitr-options.md

I've just stumbled upon [this post](https://github.com/quarto-dev/quarto-cli/issues/997#issuecomment-1139588357) and thought it makes sense to document this very convenient way to set R options for R code chunk execution. I'm not sure though, if `quarto-web/docs/computations/_knitr-options.md` is the best place. `R.options` is currently missing from [`docs/reference/cells/cells-knitr.json`](https://github.com/quarto-dev/quarto-web/blob/main/docs/reference/cells/cells-knitr.json).

Add `R.options` example

---

docs/get-started/computations/vscode.qmd

There is a typo in one of the spellings of "document"

Fixed spelling of "document"

---

docs/publishing/github-pages.qmd

Trying the example publish.yml gave me an error. Digging into it, looks like the `env` mapping needs to supplied to the step, not step.with
Failed job with the current example yml: https://github.com/t-kalinowski/tensorflow.rstudio.com/actions/runs/2677531143
Job with fixed yml (the overall job still failed, but for a different reason): https://github.com/t-kalinowski/tensorflow.rstudio.com/actions/runs/2677601915

fix GHA publish.yml examples

---

docs/faq/index.qmd

The pages https://quarto.org/docs/websites/publishing-websites.html and https://quarto.org/docs/output-formats/html-publishing.html are no longer available in the documentation. 
I have updated the links and tweaked the text to fit the new website structure and added `QuartoPub` as a publishing platform and added backticks around `_site`

Update broken links and small tweaks in FAQ

---

docs/computations/julia.qmd

The current link leads to a 404, by adding `/stable` we get to the docs

Fix link to Revise.jl docs

---

docs/websites/website-tools.qmd

This PR fixes the example YAML for enabling Open Graph, adding back in the hyphen. As written, the example doesn't work, meaning the instructions for the easy setup of Open Graph metadata don't work properly; users either need to go down to the more advanced section and notice the difference:
https://github.com/quarto-dev/quarto-web/blob/d172e572d369578c7a26d3113ace11893b62c1db/docs/websites/website-tools.qmd#L115-L120
Or check the field on an example website:
https://github.com/quarto-dev/quarto-web/blob/d172e572d369578c7a26d3113ace11893b62c1db/_quarto.yml#L14

Fix example open graph YAML

---

_quarto.yml

Uses new `logo-alt` parameter (https://github.com/quarto-dev/quarto-cli/commit/eab69da389ae4b9e9ac0c7382a6948e14939dc87) to add alt text to the navbar brand (which previously was a WCAG failure).

Add alt text for logo in navbar.

---

docs/interactive/ojs/data-sources.qmd

The relationship between Apache Arrow and Feather is very confusing to the uninitiated, so I think it is better to use the term "Apache Arrow IPC file format" as used in the official documentation and push Feather V2 into parentheses.
(c.f. https://issues.apache.org/jira/browse/ARROW-17092)
Related to quarto-dev/quarto-cli#1845

Arrow -> Apache Arrow IPC

---

docs/extensions/_formats-common.qmd
docs/extensions/formats.qmd

Just following along with creating formats docs and noticed a couple of typos.

Fix minor typos in Extensions docs

---

docs/websites/website-navigation.qmd

Old link was broken and resulted in "page not found". Hope it is fine to create a pull request immediately :)

Fix link to aria-label page by mozilla

---

docs/blog/posts/2022-06-21-rstudio-conf-2022-quarto/index.qmd

Adding in links to the rstudio::conf(2022) talk recordings for Quarto talks on the conf talks blog post, so it can be a landing page for all the Quarto talks at conf.

adding links to rstudioconf talk recordings

---

.gitignore

I got the `.luarc.json` file created automatically when opening the project in VSCODE. 
Doc saus: 
> The .luarc.json file will also be automatically added to .gitignore since it points to the absolute path of Quarto on the local system.
So we should add to `.gitignore` right ?

Add `.luaarc.json` to gitignore

---

docs/authoring/diagrams.qmd

Correct spelling is gantt, not gnatt [Wikipedia](https://en.wikipedia.org/wiki/Gantt_chart)

Fix gantt chart typo

---

docs/projects/virtual-environments.qmd

The ability to programmatically save and restore a conda environment via an `environment.yml` file is currently a functionality of `conda env`, not `conda`. Corrected the documentation to match.

Clarify saving and restoring conda env behavior

---

docs/authoring/markdown-basics.qmd

After reading the docs, I was still confused about how the markdown-flavoured divs and spans would translate into HTML.
https://quarto.org/docs/authoring/markdown-basics.html#divs-and-spans
After each markdown example, I added what the HTML output would look like. I hope this helps readers understand the div/span markdown syntax more easily.

Add examples of how markdown divs and spans translate into HTML

---

docs/websites/website-basics.qmd

The sentence "This will create the scaffolding for a simple website in the `mysite` sub-directory." was written two times.

Correcting error in website-basics.qmd

---

docs/journals/index.qmd

While previews of the different journal templates are already available from their respective repositories, they are much harder to find and compare from within the repositories.
Having the preview links readily available in the docs would be quite beneficial IMO, so I made a quick commit / PR to add them. (I can't properly verify whether all links work atm., since I'm on a limited internet connection, but will try to do so later)

Add preview links for Journal templates

---

docs/get-started/hello/rstudio.qmd

I would also opt for using the same example qmd also in the `quarto::quarto_render` example.

change rmd to qmd

---

docs/authoring/language.qmd

This documents that different alternate text values can be specified for different languages. See https://github.com/quarto-dev/quarto-cli/issues/2812

Document language-specific alternate text values

---

license.qmd

This PR update the license page to reflect the same version of Boostrap/Bootswatch as internally used by Quarto.

fix: update Bootstrap version to 5.1.3 according to code

---

_quarto.yml

Switch the website into RC mode, which will promote the pre-release into the 'Get Started' download list and will use the label `Release Candidate` for the pre-release builds.

Switch to RC Mode

---

docs/presentations/revealjs/presenting.qmd

This PR fix the last file where `self-contained` was still mentionned (inside a callout).
See <https://quarto.org/docs/presentations/revealjs/presenting.html#chalkboard>.
With this PR, #422 can be closed I think.
To note, there is one file in `_freeze` still mentionning the deprecated option: <https://github.com/quarto-dev/quarto-web/tree/main/_freeze/site_libs/revealjs/plugin/reveal-chalkboard/plugin.yml>

fix: uses `embed-resources` instead of `self-contained`

---

docs/extensions/listings/shortcodes-and-filters.yml

This PR adds the `shinylive` Quarto extension to the extension listing page on Quarto website.
This PR echoes to the recent published blog post.

docs: add shinylive filter in the extension listing

---

docs/gallery/gallery.yml

My website makes use of many different Quarto features, and as such, can show what Quarto is capable of. For example, the landing page includes a dynamic dual listing in conjunction with an about me template — this was achieved through using CSS grids. My website also features two pages that have their own listings, one which showcases the default listing style and the other showcasing the grid style. Tabsets are used in my about me page, reducing clutter. Lots of other Quarto features are sprinkled around the site, from page layouts to margin headers to figure layouts to embeds and more!
I also plan to update the website and make more use of Quarto extensions, such as the scroll-to-the-top button, text animations, and image lightboxes — the latter for when I shift my 3D CG works to the …

Including my website in the gallery.

---

docs/authoring/callouts.qmd

This PR fixes a typo in a callout example.

fix: typo in callout example

---

docs/gallery/gallery.yml

Link rot at https://quarto.org/docs/gallery/#interactive-docs

Fix broken source links in gallery for interactive docs

---

docs/extensions/listings/shortcodes-and-filters.yml

Add extension `code-insertion` to add markdown/html code immediately before or after the post.

add extension: code-insertion.

---

docs/extensions/listings/shortcodes-and-filters.yml

I created this extension to solve a problem I was having with the `README.md` generated by the `index.ipynb` file of an `nbdev` project. It seemed like the kind of thing a lot of people might see, but I couldn't find any answers.

gfm-strip-disallowed

---

docs/publishing/github-pages.qmd

While migrating [this documentation repository](https://github.com/csiro-hydroinformatics/streamflow-forecasting-tools-onboard/) to use Quarto, I am bumping into a bit of a slightly confusing step in the `Publish Command` section. Instructions state that:
> Before attempting to publish you should ensure that the **Source** branch for your repository is `gh-pages`
but typically a repository would not have a pre-existing `gh-pages` branch.
I submit a few command lines to set up an empty stub `gh-pages` branch.

Instructions to create an empty gh-pages branch

---

docs/extensions/listings/shortcodes-and-filters.yml

Currently, mutiple authors of an extension specified with the yml field "authors" are not shown on the HTML page with the listed quarto extensions. This PR indends to fix the displaying of muliple authors shown in the table that lists quarto extensions. (However, not sure if it really does so.)

fix: displaying of mutiple authors

---

docs/authoring/tables.qmd

Added the Tables Generator's Plain Text mode to the grid table tools list.
Additionally, to get the header styling, the option `Use reStructuredText syntax` inside the tool below the result needs to be checked.
I've tested it and it works fine!

[tables.qmd] added a tool for grid tables

---

docs/books/book-crossrefs.qmd

This adds a callout inside of the book section of cross references to emphasize the specific label prefix for referring to sections in a manner that is similar to the `table` subsection of cross references:
https://quarto.org/docs/authoring/cross-references.html#tables

Emphasize the `sec-` prefix similar to tbl

---

docs/publishing/github-pages.qmd

Updated the `publish.yml` GitHub Action example to use the new `actions/checkout@v3`. This resolves quarto-dev/quarto-web#569

Update publish.yml example.

---

docs/extensions/listings/shortcodes-and-filters.yml

I have created a quarto filter [`line-highlight`](https://github.com/shafayetShafee/line-highlight) to enable source code and output line highlighting for HTML documents (`format: html`) similar to how [`code-line-numbers`](https://quarto.org/docs/reference/formats/html.html#code) works for RevealJs output, which I would like to see added to the quarto extension list. Thanks 😊

added entry for line-highlight filter in shortcodes-and-filters yml

---

docs/tools/vscode.qmd

I was looking for a way to enable snippet suggestions in `qmd` files and found a stackoverflow post that explained it. I can't find it anymore though, but I'd like to add a quick guide on how to enable it. Also it seems that the Quarto extension overrides the default setting.

Added guide on how to enable snippets suggestion

---

docs/get-started/computations/text-editor.qmd

At least on Ubuntu 22.04 with Python 3.11.1, `computations.qmd` otherwise errs with:
```
$ quarto preview computations.qmd
Starting python3 kernel...Done
Executing 'computations.ipynb'
Cell 1/3...Done
Cell 2/3...Done
Cell 3/3...ERROR: 
An error occurred while executing the following cell:
------------------
import plotly.express as px
import plotly.io as pio
gapminder = px.data.gapminder()
gapminder2007 = gapminder.query("year == 2007")
fig = px.scatter(gapminder2007, 
x="gdpPercap", y="lifeExp", color="continent", 
size="pop", size_max=60,
hover_name="country")
fig.show()
------------------
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[3], line 1
----> 1 import plotly.express …
```

Adds `pandas` to `computations.qmd` tutorial

---

docs/extensions/listings/revealjs.yml
docs/extensions/listings/shortcodes-and-filters.yml

I have made two filters for revealjs output format, [`reveal-header`](https://github.com/shafayetShafee/reveal-header) and [`style-speaker-note`](https://github.com/shafayetShafee/style-speaker-note), and added these two in the revealjs.yml listings. I have actually made these filters by extending the idea of the answers (answered by me) to the following questions in Stackoverflow,
- https://stackoverflow.com/questions/74616971/quarto-revealjs-header-on-all-slides
- https://stackoverflow.com/questions/75213819/how-to-change-the-default-font-size-in-quarto-speaker-notes/
- https://stackoverflow.com/questions/74060565/adding-a-logo-at-top-left-corner-for-all-slides-in-quarto-presentation/

added two filters for revealjs in revealjs listings

---

docs/websites/website-blog.qmd

Small change to reflect that category feeds appear to use kebab-case rather than snake case (at least for me with quarto version `1.2.335`).

Update filename of category feeds

---

docs/computations/julia.qmd

Until https://github.com/quarto-dev/quarto-cli/issues/2539 is resolved, alert the use to an issue and workaround for using Julia 1.8.4+

Add warning about julia issue

---

docs/reference/formats/docx.json

Regenerate Reference section based on change to schema (https://github.com/quarto-dev/quarto-cli/pull/4268). Fixes #608

Regenerate docx reference to remove code-line-numbers as an option

---

docs/authoring/cross-references.qmd

This doesn't seem to work
```
---
crossref:
title-delim: -
---
```
but this does
```
---
crossref:
title-delim: "-"
---
```

Fix quotes for title-delim

---

_quarto.yml
about.qmd
docs/faq/index.qmd
docs/faq/rmarkdown.qmd
docs/guide/guide.yml
docs/interactive/shiny/running.qmd
docs/output-formats/html-publishing.qmd
docs/presentations/revealjs/presenting.qmd
docs/projects/environment.qmd
docs/publishing/ci.qmd
docs/publishing/index.qmd
docs/publishing/other.qmd
docs/publishing/rstudio-connect.qmd
docs/websites/website-basics.qmd
docs/websites/website-blog.qmd
index.qmd
license.qmd
trademark.qmd

Update documentation site for name change to Posit.
In particular:
- Footer logo and link
- References to Posit the company, and commercial products (e.g. RStudio Connect -> Posit Connect)
I updated URLs that pointed to the RStudio home page, but didn't touch any other URLs on the rstudio.com domain assuming the redirects will take care of them.
Fixes #612

RStudio -> Posit

---

docs/computations/julia.qmd

for quarto-dev/quarto-cli#2539
This follows fix in https://github.com/quarto-dev/quarto-cli/pull/4263
@cscheid  is that fix now in pre-release right ? 
It seems to me the workaround to install latest 1.3 is better than running with no daemon. 
But maybe both should be shared. 🤷‍♂️

Adapt Julia callout warning following 1.3 bug fix

---

docs/websites/website-blog.qmd

The YAML header field `date-modified` is implemented (see [this issue](https://github.com/quarto-dev/quarto-cli/issues/1241)) but not documented yet. As this is an important feature when updating blog posts, it seems reasonable to include it in the main documentation.
Feel free to adjust the phrasing as needed.

Add documentation for date-modified (blogs)

---

docs/prerelease/1.3/pdf.qmd

`brew install libsvg` doesn't install `rsvg-convert` (but libsvg is a valid package, which made for a short puzzle). This fixes that tiny typo and revises a couple of other references to librsvg instead of libsvg.

Correct name of package to install with brew

---

docs/get-started/hello/jupyter.qmd

In the existing instructions only jupyter was installed, not jupyterlab though. After installation, jupyter lab also throws an error if you don't run the "build" step before using it.
Tested on a Mac with python version 3.10.9 and jupyter lab version 3.6.1. Assuming Linux and Windows behave the same.

Update installation instructions for jupyterlab

---

docs/extensions/listings/revealjs-formats.yml
docs/extensions/listings/revealjs.yml

I have added a custom format [`metropolis-revealjs`](https://github.com/shafayetShafee/metropolis) in the revealjs-formats.yml file.
Also changed my name to my full name for the previously added revealjs filter. And I have also added [`code-fullscreen`](https://github.com/shafayetShafee/code-fullscreen) in the revealjs listing. 
Note that, `code-fullscreen` already exists in the shortcode and filter listing, but I have added it in the reveals listing too, because I believe it is more useful when used in revealjs presentations.

Added a custom format for revealjs

---

docs/presentations/revealjs/index.qmd

Otherwise, following warning will be displayed: `WARNING: output-location is only valid for cells that echo their code` and code won't be displayed

output-location is valid when echo is set to true

---

docs/prerelease/1.3/tables.qmd

For the v1.3 prerelease notes, a short section on Bootstrap table class support (insertable via table caption) has been added here.

Add section on Bootstrap table class support

---

docs/authoring/cross-references.qmd

i was going a little crazy as a beginner as to why my reference wasn't working. From guessing and testing it was because i had a couple of uppercase letters sprinkled in. Thought it should be added in the docs. Not sure if there are other simple rules to know but from now on ill be sticking to only hyphens, numbers, and lowercase. Cheers.

Specify Cross Ref identifier case constraint

---

docs/extensions/listings/shortcodes-and-filters.yml

Tested with Quarto and Pandoc, a filter to handle self-citing bibliographies (e.g. BibTeX containing `\citet` commands).

Lists recursive-citeproc filter

---

docs/faq/rmarkdown.qmd
docs/get-started/authoring/rstudio.qmd
docs/get-started/computations/rstudio.qmd
docs/get-started/hello/rstudio.qmd
docs/interactive/shiny/running.qmd
docs/tools/_rstudio.md
docs/visual-editor/index.qmd

Newest RStudio version 2023.03 is now mentioned and recommended. Clarified that at least v2022.07 is required to work with some of the integrated Quarto features. Links updated to new posit.co website.

Updated RStudio version and link to posit.co

---

docs/get-started/hello/rstudio/_hello.qmd

Fixes <https://github.com/quarto-dev/quarto-cli/issues/4973>
It appears screenshots for RStudio tutorial were updated last year with a different title, but the Quarto document for user to download was not.

fix: qmd title inconsistent with screenshots

---

_variables.yml
docs/authoring/diagrams.qmd
docs/authoring/videos.qmd
docs/blog/posts/2022-07-25-feature-extensions/index.qmd
docs/extensions/_extension-version.qmd
docs/extensions/lua-api.qmd
docs/extensions/lua.qmd
docs/extensions/project-types.qmd
docs/faq/rmarkdown.qmd
docs/get-started/authoring/rstudio.qmd
docs/get-started/computations/rstudio.qmd
docs/get-started/hello/rstudio.qmd
docs/interactive/shiny/running.qmd
docs/journals/templates.qmd
docs/output-formats/_ssg-intro.qmd
docs/output-formats/html-basics.qmd
docs/output-formats/html-code.qmd
docs/output-formats/html-themes.qmd
docs/output-formats/pdf-engine.qmd
docs/presentations/revealjs/advanced.qmd
docs/projects/environment.qmd
docs/projects/profiles.qmd
docs/reference/projects/_options.md
docs/tools/_rstudio.md
docs/tools/rstudio.qmd
docs/tools/vscode.qmd
docs/visual-editor/index.qmd
docs/websites/website-navigation.qmd

Remove references to require Quarto versions <= 1.2
Standardize references to Rstudio versions using variables.
Closes [#4463](https://github.com/quarto-dev/quarto-cli/issues/4463)

Update references to old Quarto versions and RStudio versions

---

docs/journals/authors.qmd

- trivial typo
- clarify that only unique affiliations are listed in affiliations – I assume this is the case, but it's not explicitly stated

State unique affiliations (?) in authors.qmd

---

docs/extensions/listings/shortcodes-and-filters.yml

Here is a filter I made to handle critic markup syntax that we use extensively for academic writing since it allows us to easily track contributors' modifications.
There are a few things that could be added such as options to choose which version to export but I think this would still be a good addition to the community.
Here is the rendered example for illustration
https://mloubout.github.io/critic-markup/

Update shortcodes-and-filters.yml with critic-markup filter

---

docs/extensions/listings/custom-formats.yml

Changed "hikmax" to "hikmah"
(addresses https://github.com/andrewheiss/hikmah-academic-quarto/issues/3)

Fix typo in title of extension

---

docs/authoring/notebook-embed.qmd

Needed to add `shortcodes=false` to examples

Fix Notebook Embed docs to show example shortcodes

---

docs/publishing/github-pages.qmd

This PR add[^1] a description of the publish action and add a statement about specifying/checking the write permission for GitHub Actions to write in `gh-pages`.
Default was changed to "read-only" few months back, thus it requires to add write permission for newly created repository.
[^1]: in the following page/section: <https://quarto.org/docs/publishing/github-pages.html#publish-action>

docs: add GHA permission documentation

---

docs/authoring/figures.qmd

Hi,
there is a small typo in LaTex figure position setting.

Fixed typo in fig-pos

---

docs/interactive/ojs/index.qmd

Following this [discussion ](
https://github.com/quarto-dev/quarto-cli/discussions/5680)I thought an additional note in the OJS section about the file protocol not working might be useful. 
Let me know if there is a better place for this or if the discussion is sufficient and the note is overkill. 
My intended use case was to send HTML files for another user to open so this piece of information was important.

Add note that OJS won't work using the file protocol. 

---

tools/reference.ts

`parse()`, as of 0.180.0, lives in `std/yaml/mod.ts`

Update deno dependency path

---

docs/extensions/listings/custom-formats.yml

Adds the fancy-doc Quarto extension that contains a custom PDF template to the list of custom formats on the Quarto Extensions section of the webpage.

add fancy-doc extension to custom-formats list of Quarto extensions

---

docs/output-formats/html-multi-format.qmd

Prepends a slash `/` to the Project Metadata path, so that the link is resolved to:
- https://quarto.org/docs/projects/quarto-projects.html#project-metadata
instead of the current
- https://quarto.org/docs/output-formats/docs/projects/quarto-projects.html#project-metadata

Fix broken link for "Project Metadata" in `html-multi-format.qmd`

---

docs/get-started/computations/_computations-complete.qmd

The plots in @fig-mpg show the relationship between city and highway mileage for 38 popular models of cars.
In @fig-mpg-1 the points are colored by the number of cylinders while in @fig-mpg-2 the points are colored by engine displacement.

Corrected text Update _computations-complete.qmd

---

.github/workflows/preview.yml
.github/workflows/publish.yml
.github/workflows/upload-index.yml
docs/publishing/github-pages.qmd
docs/publishing/netlify.qmd
docs/publishing/quarto-pub.qmd
docs/publishing/rstudio-connect.qmd

GitHub is entering its final deprecation stage of Node12 which is used in the checkout v2 action.
See <https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/>.
Actions in <https://github.com/quarto-dev/quarto-actions> are already using V3, but the website was still showing v2.
This PR fixes the actions, in the website itself and in the CI of this repository.

fix: github action checkout v2 deprecated

---

docs/extensions/listings/shortcodes-and-filters.yml

I made a simple extensions that allows users to edit the horizontal rule output for .docx files, since that wasn't editable (as far as I could work out) in a reference-doc. Thought I would share in case you think it's useful for more users

Propose Adding docx-horizontal-rule extension

---

docs/manuscripts/index.qmd

Here's a proposed tweak to the overview language. The main thing I did was:
(1) Try to distinguish manuscripts from normal notebooks or qmds by mentioning that you can use "one or more" of them (to me just saying "Link your computations to your narrative, allowing your readers to dive into your code" isn't quite enough to see why this is something new).
(2) Punch up the emphasis of "multiple formats" available through the website (again to distinguish from a normal article you might publish)
(3) Eliminate the reference to MECA bundles in the intro (too much to try to communicate/understand, and in the early days this will only be interesting to users that have been pointed to us from a journal that is prepared to accept MECA submissions.

tweak overview language

---

docs/computations/_jupyter-cache.md
docs/computations/_jupyter-install.md
docs/computations/caching.qmd
docs/computations/julia.qmd
docs/get-started/computations/jupyter.qmd
docs/get-started/computations/text-editor.qmd
docs/get-started/computations/vscode.qmd
docs/get-started/hello/jupyter.qmd
docs/get-started/hello/neovim.qmd
docs/get-started/hello/text-editor.qmd
docs/get-started/hello/vscode.qmd
docs/projects/virtual-environments.qmd
docs/tools/jupyter-lab-extension.qmd
docs/tools/jupyter-lab.qmd

This PR tweaks the code blocks in tables to allow the copy button which make it easier to use the code showed.
It also makes the OS order consistent across the website.
| Before | After |
|--------|-------|
| <img width="877" alt="image" src="https://github.com/quarto-dev/quarto-web/assets/8896044/beed0219-f707-4a41-a0b0-cc36dc81ba9a"> | <img width="877" alt="image" src="https://github.com/quarto-dev/quarto-web/assets/8896044/1e52168b-4ff3-48a8-8f3a-ea3a26e9841d"> |

style: allow code block to be copied using the copy button

---

index.qmd

`d.date.getUTCDate()` returns `TypeError: d.date.getUTCDate is not a function`. Use `new Date(d.date).getDate()` instead.

Update OJS example in index.qmd

---

docs/authoring/figures.qmd

Closes https://github.com/quarto-dev/quarto-cli/issues/4954

Add link to global figure options from figure page

---

_quarto.yml
docs/reference/cells/index.qmd
docs/reference/cells/reference.yml
docs/reference/index.qmd

I'd like to provide a link on the cheatsheet for where people can learn about other code cell options. Currently, I'd need to list both a knitr and jupyter link because there is no common landing page (except the top-level Reference page).
I'm not sure if there is a less duplicative approach than what I did here (copying part of the top-level `reference.yml`)...
Also open to what text might be on this landing page.

Add a landing page for Reference > Code Cells

---

docs/extensions/managing.qmd

Originally discussed in https://github.com/quarto-dev/quarto-cli/issues/5827#issuecomment-1578271647
This PR intends to make it explicit that extensions can be bundle as `.zip` or `.tar.gz` archive (as explicilty stated in other pages but `/Users/mcanouil/Projects/quarto/quarto-web/docs/extensions/managing.qmd`).

docs: makes it clear zip an tar.gz are supported

---

docs/extensions/_formats-common.qmd

This PRs fixes and improves the documentation for extension embedding.
The example was to embed extension in an installed extension, which actually should never happen in user, but instead you want to embed extension when developping one.
In addition, the `jss` / `fancy-text` example now got adirectory tree to clearly show that embedding means adding an extension within an extension.
This is related to quarto-dev/quarto-cli#6291

fix: extension embedding example

---

docs/extensions/listings/journal-articles.yml

The American Political Science Review is one of the primary journals in political science. This adds a Quarto template for the APSR to listing page.
The template is on GitHub, has a[ `readme.md`](https://github.com/christopherkenny/apsr/blob/main/README.md) file, and is licensed under MIT (for the Quarto part) and CC BY 4.0 (for the underlying LaTeX template).

Add journal article template for the APSR to listing

---

docs/authoring/diagrams.qmd

Makes more explicit that an .mmd file can be used as an external source when including a Mermaid diagram in a .qmd document, as this is made more explicit for .dot files in the current version of the docs.
Mermaid and Graphviz diagrams can be included in `.qmd` documents from external files.
In the docs an example is given for how to achieve this
using a Graphviz diagram defined in a `.dot` file.
This minor change makes it more explicit that an appropriate filetype
that would achieve the same for a Mermaid diagram is `.mmd`.
The `.mmd` filetype is mentioned two sections previous
in the context of specific editors (RStudio, VS Code).
Readers of the docs are likely to benefit from seeing
the relevant filetypes close to their implementation in the File Include section of the docs,
especially …

docs: explicit reference to filetype for .mmd File Includes

---

docs/extensions/listings/shortcodes-and-filters.yml

This extension adds a lua extension to render D2 diagrams in a quarto document.
Example:
````markdown
---
title: "D2 Example"
filters:
- d2
---
```{.d2}
logs: {
shape: page
style.multiple: true
}
user: User {shape: person}
network: Network {
tower: Cell Tower {
satellites: {
shape: stored_data
style.multiple: true
}
satellites -> transmitter
satellites -> transmitter
satellites -> transmitter
transmitter
}
processor: Data Processor {
storage: Storage {
shape: cylinder
style.multiple: true
}
}
portal: Online Portal {
UI
}
tower.transmitter -> processor: phone logs
}
server: API Server
user -> network.tower: Make call
network.processor -> server
network.processor -> server
network.processor -> server
server -> logs
server -> logs
server -> logs: persist
server -> network.portal.UI: display …

Add an entry for the quarto-d2 filter

---

docs/tools/vscode-notebook.qmd

Fixed small typo: changed "Output Outputs" to "Output Options"

Fix typo in vscode-notebook.qmd

---

docs/publishing/github-pages.qmd
docs/publishing/netlify.qmd
docs/publishing/quarto-pub.qmd
docs/publishing/rstudio-connect.qmd

This PR updates the documentation to use the checkout GitHub Actions v4.
See <https://github.com/quarto-dev/quarto-actions/pull/86> for action repository already updated.
Checkout action release: https://github.com/actions/checkout/releases/tag/v4.0.0

chore: update checkout action to v4

---

docs/interactive/ojs/libraries.qmd

The URL has changed, so use the apex url now.
Fixes quarto-dev/quarto-cli#6862

fix: use default base url for jsdelivr

---

docs/presentations/revealjs/themes.qmd

I enjoyed the way the tables were split into categories on the [html sass variables](https://quarto.org/docs/output-formats/html-themes.html#sass-variables), and thought it would be neat if that could be replicated on the revealjs side

split up revealjs sass variables table into multiple

---

docs/presentations/revealjs/advanced.qmd

This feature is not officially documented on the revealjs website, but the source is here: https://github.com/hakimel/reveal.js/blob/713702a0ab81d1756a30e6c14ae49afd42135541/js/reveal.js#L1650-L1659
Added back in 2012: https://github.com/hakimel/reveal.js/issues/70
Mentioned in news: https://github.com/hakimel/reveal.js/releases/tag/2.6.0
> Added support for per-slide vertical centering, simply add a .center class to the <section>
It is super neat and should be used

document center class in revealjs

---

docs/tools/_jupyter-lab-extension-install.qmd

This PR fixes a typo in the version number of jupyterlab (*i.e.*, an extra dot).

fix: typo in jupyterlab-quarto version

---

docs/websites/website-listings.qmd

This PR fixes the documentation which states the option to add file or external links is `href` when it is `path` (or at least the latter works as most users expect it to work).
This is from at least two feedback this week:
- https://github.com/quarto-dev/quarto-cli/issues/4903#issuecomment-1736357397
- https://github.com/quarto-dev/quarto-cli/discussions/6338
- https://github.com/quarto-dev/quarto-cli/discussions/6309
CC @dragonstyle

fix: href does not exist, correct is path

---

docs/gallery/gallery.yml

Looks like the certificate only works with `www`, fixed here

fix gallery link to secure

---

docs/authoring/language.qmd
docs/output-formats/html-basics.qmd
docs/visual-editor/vscode/index.qmd

Fix various typos

---

docs/publishing/github-pages.qmd

the apostrophe in
```sh
git reset --hard # make sure you've committed changes before running this!
```
was causing vscode to look for the matching apostrophe and was not running the code in the block and returning a `quote>` prompt

update terminal comment to not use an apostrophe

---

docs/extensions/listings/journal-articles.yml

IEEE is one of the most famous scientific associations in the fields of engineering. It is the publisher of hundreds of peer-reviewed transactions, journals and magazines in various fields (e.g. electronics, computer engineering, control, biomedical, etc.).
This adds the [quarto-ieee] template, which supports the [`IEEEtran`](https://ctan.org/pkg/ieeetran)  LaTeX document class for PDF output. In addition, the HTML output is supported, and attempts to mimic as closely as possible the paper layout seen on [IEEEXplore<sup>®</sup>](https://ieeexplore.ieee.org/).
The [quarto-ieee] template is hosted on Github, includes a [`README.md`](https://github.com/dfolio/quarto-ieee#readme), and is licensed under the MIT.
[quarto-ieee]: <https://github.com/dfolio/quarto-ieee>

Add  quarto-ieee template for IEEE transaction/journal

---

docs/prerelease/1.4/script.qmd

update docs to use python f-strings instead of `.format()` notation

use python f-strings in script.qmd

---

docs/authoring/cross-references.qmd

The callout-note was showing up as part of the code example, which I don't think was what was intended.

Code listings: render the callout

---

docs/dashboards/reference.qmd

From a `localhost` link to `components.qmd#pages`

docs(dashboards): Fix link to Pages in dashboard components

---

docs/dashboards/layouts.qmd

Fixes minor typo, 'are' to 'as'.

Fix typo in layouts.qmd

---

docs/prerelease/1.4/typst.qmd

Lines 43 and 47 of `typst.qmd` were duplicates. I removed line 47, since line 43 seemed to be the more appropriate position in the table (after the `toc` and `section-numbers` options).

Remove duplicate section-numbering option in Typst documentation

---

docs/authoring/create-citeable-articles.qmd

Editing name particles is addressed with a link to the CSL specification section on naming particles.

Mention use of name particles with reference link

---

docs/projects/environment.qmd

Inserted "or" in environment.qmd

---

docs/authoring/tables.qmd

The R instructions call `kable` *twice* to produce the 2 tables, but in python calling `Markdown` twice does not work. Instead I found that `Markdown(table1 + table2)` seems to work, so I created a `tabset` with instructions for R and Python.

Added tabset explaining creating subtables in a python computation block

---

docs/download/_download.html

The PR contains a modification of the Quarto Download button to incorporate in the release date of the Quarto version.
The change was discussed in: https://github.com/quarto-dev/quarto-cli/discussions/7549
Before:
After:
**Note:** This will apply the change across all instances of the Quarto download button, e.g. 
- https://deploy-preview-915--mystifying-jepsen-fa4396.netlify.app/docs/download/
- https://deploy-preview-915--mystifying-jepsen-fa4396.netlify.app/docs/download/prerelease
- https://deploy-preview-915--mystifying-jepsen-fa4396.netlify.app/docs/get-started/
[Edited by @cwickham to link to live preview of PR build]
(There may be more...)

Modify the download button to incorporate the release date of the Quarto version

---

docs/extensions/listings/custom-formats.yml
docs/extensions/listings/revealjs-formats.yml

This fixes a typo in a format name and add `invoice-typst` format extension to create invoices with Quarto and Typst.

feat: add quarto invoice-typst format

---

docs/get-started/authoring/_text-editor.md

In line 54, the geometry parameters were "left=20mm".
In line 84, the geometry parameters of the same code block now reads "left=30mm". 
This difference is most likely a typo error. I fixed it so that both line 54 and line 84 reads "left=20mm". Hopefully this will reduce confusion among more novice learners.

Update _text-editor.md to fix typo in line 84

---

docs/prerelease/1.4/_highlights.qmd
docs/prerelease/1.4/email.qmd

This adds v1.4 release notes for the Connect emailing feature introduced in https://github.com/quarto-dev/quarto-cli/pull/6181.

Prerelease notes/howto for Connect email feature

---

_quarto.yml
docs/prerelease/1.4/_highlights.qmd

Adds sidebar nav to the 1.4 highlights page [[Preview](https://deploy-preview-932--mystifying-jepsen-fa4396.netlify.app/docs/prerelease/1.4)]
For features that aren't already integrated into main docs (e.g. not manuscripts or dashboards), improves:
* Navigation between 1.4 highlights 
* Context through the "Quarto 1.4 Highlights" breadcrumb
For example:

Improve 1.4 prerelease navigation

---

docs/books/book-structure.qmd

Currently, the documentation for books only mention level-one header and YAML title, while in the absence of those, the first header found (independently of its level) will be promoted to title.

docs: add note about header promotion in book

---

docs/prerelease/1.4/lua_changes.qmd

I believe the names used in our codebase are not the one documented 
https://github.com/quarto-dev/quarto-cli/blob/fca967e5e541542a27a5f86d3978e6b28e03ac16/src/resources/schema/definitions.yml#L40-L49
https://github.com/quarto-dev/quarto-cli/blob/fca967e5e541542a27a5f86d3978e6b28e03ac16/src/resources/filters/main.lua#L423-L440
So I changed the doc to use `pre-` and `post-` instead of `before-` and `after-`

AST processing phases have change of names

---

docs/prerelease/1.4/lua_changes.qmd

I should have merged to `main` since this applies to our currently available highlights.
This reverts commit e253967a9d26b7746ca31c6570cc25a13ec443eb.

Revert "AST processing phases had a change of names (#970)"

---

docs/authoring/cross-references-divs.qmd
docs/extensions/project-types.qmd

This commit removes some remaining links to other documentation pages or anchors which pointed at absolute localhost versions instead of relative html links, presumably leftover from dev previewing.
This should fix all remaining actually false localhost links, leaving `localhost:` in all locations where it is actually desired. 
Hope this is the right format to present the small PR in!

Fix localhost links to documentation

---

docs/dashboards/index.qmd
docs/dashboards/interactivity/shiny-r.qmd

As Quarto 1.4 is released, the pre-release callout on the Dashboard documentation page can be removed.

Remove Quarto 1.4 pre-release callout

---

docs/output-formats/docusaurus.qmd
docs/projects/binder.qmd

I am using the qmd documents in this repo as a way of checking the parsing functionality of [parsermd](https://github.com/rundel/parsermd) and I came across a couple of small inconsistencies in a couple of the documents that I believe are unintentional typos.
This pull request has these corrections which were needed to get things to work correctly with parsermd's parser.

Small typos found in quarto syntax

---

bug-reports.qmd

This PR refactor the bug report page to make it easier to understand with copy/pastable examples.
Proposed:

refactor: bug report page with examples

---

docs/projects/virtual-environments.qmd

Follow up from https://github.com/quarto-dev/quarto/issues/341

Update conda env docs

---

docs/reference/projects/navbar.json
tools/reference.ts

`navbar: right:` "left" -> "right" at: https://deploy-preview-1015--mystifying-jepsen-fa4396.netlify.app/docs/reference/projects/websites.html#navbar
Closes https://github.com/quarto-dev/quarto-cli/issues/8676

Fix typo in navbar reference

---

.github/workflows/preview.yml
.github/workflows/publish.yml
.github/workflows/update-downloads.yml
.github/workflows/upload-index.yml
docs/publishing/posit-cloud.qmd

We need to switch to avoid deprecation of Node 16. 
Opening PR just to be sure main workflow are still working. Should be ok

[gha] Update actions to checkout@v4

---

docs/output-formats/pdf-engine.qmd

This relates to https://github.com/quarto-dev/quarto-cli/issues/8897 while there was confusion on what is possible.
The example given initially was also not working 
````yaml
pdf-engine: lualatex
pdf-engine-opt: -outdir=out
```` 
This PR fix this and improve the doc by adding usage of `pdf-engine-opts` and prefer it over `pdf-engine-opt` as a string due to possible Pandoc's issue.

Fix and improve doc on pdf-engine-opts

---

docs/websites/_page-navigation.md

They need to be internal link to support `.html` transformation correctly.
This fixes https://github.com/quarto-dev/quarto-cli/issues/8902
As noted by @mcanouil, there is quite a number of links that are using absolute links starting with `https://quarto.org` instead of internal links started with `/docs/...`
@cwickham we are not sure if we are missing something regarding usage of absolute links. Probably internal links could be used instead (so that they work correctly locally or on preview for example). 
@mcanouil offered to make a PR is needed. 
Thanks

Fix internal links using `.qmd`

---

.github/workflows/publish.yml
.github/workflows/update-downloads.yml

We shouldn't publish each time update-downloads run, so just trigger publish when required

[GHA] Trigger publishing only when changes detected when regenerating (pre)release information

---

docs/output-formats/html-basics.qmd

Chromium-based browsers support MathML as of January 2023. Firefox and Safari already did.

Update MathML note

---

docs/presentations/revealjs/presenting.qmd

I'm confirming that the instructions for printing a Revealjs presentation into PDF work perfectly for Firefox, too.
I'm also changing the text to reflect that.

Confirming printing to PDF in Firefox

---

docs/extensions/starter-templates.qmd

Simple typo fix for the docs in [starter-templates.qmd](https://github.com/quarto-dev/quarto-web/blob/main/docs/extensions/starter-templates.qmd).
Changed "All of the files in the repository are copied save for:" to "All of the files in the repository are copied except for:".
***
I noticed this while reading the [starter templates documentation](https://quarto.org/docs/extensions/starter-templates.html):

[Typo]: Fixed a very simple typo in `starter-templates.qmd`

---

docs/output-formats/typst.qmd

Add a part about typst using svg as defauilt fig-format and how to change to raster if needed.
Add this precision in the documentation based on feedback at https://github.com/quarto-dev/quarto-cli/issues/7716#issuecomment-2038352708 
I think it could be useful to have this mention quickly in typst doc directly.

Document default fig-format being svg for typst

---

docs/extensions/lua.qmd

GH Wiki is displaying a deprecation warning at the top of the page:
This wiki has been replaced by the wiki on our website. This wiki will be removed in the future.
The warning redirects to update bookmarks to:
https://luals.github.io/wiki/<page>/

Switch from URL from GH Wiki (deprecated) to Lua Site Wiki

---

docs/extensions/project-types.qmd

Most other extension documentation uses `quarto-required`, not `quarto-version`. It appears that `quarto-required` is the correct field.

quarto-required not quarto-version

---

docs/extensions/filters.qmd
docs/extensions/shortcodes.qmd
docs/projects/binder.qmd

This pull request fixes the file extensions of the aliases in the documentation files. The aliases were previously using the .qmd extension instead of the correct .html extension.
Fixes quarto-dev/quarto-cli#9494

fix: aliases use qmd instead of html

---

docs/extensions/listings/shortcodes-and-filters.yml

This pull request adds an extension filter to ease formatting of text in various format, in particular setting foreground and background colours.

feat: add mcanouil/quarto-highlight-text filter

---

docs/publishing/ci.qmd

I could not find which Confluence environmental variables are valid. I wasn't sure where it was most appropriate to document them. I put them on the CI page, but perhaps the Confluence page would be even better. I chose CI since there were other env vars there. 
This was the only location where I found these env vars defined: https://github.com/quarto-dev/quarto-cli/discussions/6915

document confluence env vars

---

docs/download/tarball.qmd

On many Linux distributions, both `~/bin` and `~/.local/bin` will be automatically put on PATH, thanks to this common snippet in the /etc/profile file:
PATH=/usr/local/bin:/usr/bin:/bin
if test "$HOME" != "/" ; then
for dir in $HOME/bin/$CPU $HOME/bin $HOME/.local/bin/$CPU $HOME/.local/bin ; do
test -d $dir && PATH=$dir:$PATH
done
fi
So, it is prudent to suggest that users check this before modifying their .profile file. Furthermore, while `~/bin` has been informally used for a while, `~/.local/bin` is part of the XDG Base Directory Spec, which is increasingly embraced by the Linux ecosystem.

Suggest linux users put execs in ~/.local/bin

---

docs/prerelease/1.5/_highlights.qmd

From now on, pre-release highlights will live on the pre-release site. 
Highlights appear on:
* [1.5 Pre-release page](https://deploy-preview-1106.quarto.org/docs/prerelease/1.5/)
* [Pre-release download page](https://deploy-preview-1106.quarto.org/docs/download/prerelease)

Refer to pre-release site for highlights

---

bug-reports.qmd
docs/authoring/variables.qmd
docs/dashboards/data-display.qmd
docs/dashboards/theming.qmd
docs/output-formats/_theme-variables.md
docs/output-formats/typst.qmd
docs/troubleshooting/index.qmd
docs/websites/website-navigation.qmd

Edits based on items in changelog as of 5ec7da0 06/06/24:
Added example to: /docs/websites/website-navigation.html#breadcrumbs
Added example to: /docs/output-formats/typst.html#table-of-contents
Added example to /docs/authoring/variables.html#env
Updated example output in `bug-reports.html` and `docs/troubleshooting/`
Added conditionally to `_theme-variables.md` which gets included in: `docs/dashboards/theming.html#sass-variables`
Closes: https://github.com/quarto-dev/quarto-cli/issues/9487

Updates based on changelog

---

README.md
style-guide.md

With prior work closes https://github.com/quarto-dev/quarto-cli/issues/4496
Closes https://github.com/quarto-dev/quarto-cli/issues/9099

Updates to README

---

docs/extensions/filters.qmd

The suggestion to not use the same filename as the extension name was complicated by the fact that is what `quarto create extension filter` does. 
Instead I attempted to clarify when `example.qmd` is mentioned.
Also, swapped out `lightbox` example since this extension is now bundled in Quarto.
Closes https://github.com/quarto-dev/quarto-cli/issues/6754

Clarify using extension name not filter file name to `filter`

---

docs/advanced/environment-vars.qmd
docs/advanced/index.qmd
docs/advanced/jupyter/kernel-execution.qmd

* Listing page at `docs/advanced/index.qmd`: [Preview](https://deploy-preview-1145.quarto.org/docs/advanced/)
* Not included in search (but pages in `docs/advanced` are)
* Not linked from navigation
* Drafts will not appear in published listing, but will appear in previews

Advanced Docs Landing Page

---

docs/output-formats/html-multi-format.qmd

Adds example in [Guide > HTML > Including Other Formats](https://deploy-preview-1167.quarto.org/docs/output-formats/html-multi-format.html#specifying-formats-to-link)
Closes https://github.com/quarto-dev/quarto-cli/issues/8610

Add example of customizing format-links

---

_quarto.yml
docs/authoring/citations.qmd
docs/authoring/markdown-basics.qmd
docs/get-started/authoring/_text-editor.md
docs/get-started/authoring/jupyter.qmd
docs/get-started/authoring/rstudio.qmd
docs/guide/guide.yml
docs/manuscripts/authoring/_citations.qmd
docs/output-formats/_pdf-citations.md
docs/output-formats/typst.qmd

Closes https://github.com/quarto-dev/quarto-cli/issues/9964
Footnotes move to: [Guide > Authoring > Markdown Basics](https://deploy-preview-1188.quarto.org/docs/authoring/markdown-basics.html#footnotes)
Citations are now stand-alone: [Guide > Authoring > Scholarly Writing > Citations](https://deploy-preview-1188.quarto.org/docs/authoring/citations.html)

Move footnotes to markdown basics

---

docs/journals/templates.qmd

Adds Typst Partials: [Preview](https://deploy-preview-1202.quarto.org/docs/journals/templates.html#typst-partials)
Closes https://github.com/quarto-dev/quarto-cli/issues/8500

Document Typst partials with other partials

---

docs/reference/projects/_options.md
docs/reference/projects/_websites-pre.md
docs/reference/projects/_websites.md

[Reference > Websites](https://deploy-preview-1201.quarto.org/docs/reference/projects/websites.html):
* Add examples to each section
* Ensure project options are in a ` ```{.yaml filename="_quarto.yml"}` cell, and document options in ` ``` yaml ` cell with `---`.
Closes https://github.com/quarto-dev/quarto-cli/issues/7869

Improve context on Reference > Websites

---

docs/presentations/_creating-slides.md
docs/presentations/beamer.qmd

Adds example of block environments to: [Guide > Presentations > Beamer](https://deploy-preview-1206.quarto.org/docs/presentations/beamer.html#creating-slides)
Plus some other minor improvements
Partially addresses https://github.com/quarto-dev/quarto-cli/issues/5617

Add example of block environment for beamer slides

---

_quarto-prerelease-docs.yml

I think I put the `algolia: index-name` in before we were using profiles. This undoes the change in `_quarto.yml` and instead sets it in `_quarto-prelease-docs.yml`:
```
website:
search:
algolia:
index-name: prerelease_QUARTO
```

Set Algolia index in prerelease-docs profile

---

docs/extensions/listings/shortcodes-and-filters.yml

This filter implements citation macros for United States House and Senate bills, resolutions, and amendments. Given a short citation like `118hr8070` between curly brackets (a.k.a. braces &mdash; `{}`),  the rendered Quarto document will display a link to the bill, resolution, or amendment referenced by the citation on Congress.gov.

Add `leg-cite` filter

---

docs/download/changelog/1.1/_changelog.md
docs/download/changelog/1.1/index.qmd
docs/download/changelog/1.2/_changelog.md
docs/download/changelog/1.2/index.qmd
docs/download/changelog/1.3/_changelog.md
docs/download/changelog/1.3/index.qmd
docs/download/changelog/1.4/_changelog.md
docs/download/changelog/1.4/index.qmd
docs/download/index.qmd
docs/download/prerelease.qmd
docs/download/release.qmd

A rather manual take on having release notes in permanent locations on quarto.org of the form `quarto.org/docs/download/changelog/1.*/` (e.g. [1.4](https://deploy-preview-1250.quarto.org/docs/download/changelog/1.4/)). 
Available via links from "Older Releases" tab. Current and prerelease are aliased to their respective pages.
We would have to add the following tasks to the release checklist:
* Copy `changelog` from old release to `_changelog.md` in `docs/download/changelog/1.x`
* Copy `docs/download/changelog/1.*/index.qmd` and increment versions
* Add new item to `download-older` listing in `docs/download/index.qmd` 
* Increment version in `aliases` of:
- `docs/download/release.qmd`
- `docs/download/prerelease.qmd`
Would close https://github.com/quarto-dev/quarto-cli/issues/5396

Add pages for release notes

---

license.qmd

Following discussion at https://github.com/quarto-dev/quarto-cli/discussions/10319#discussioncomment-10084294, we noticed this page was outdated regarding some version information. 
This PR update it, and add two more entries of tools we ship and use as external tooling 
- Typst for PDF generation
- Juice that we call from Pandoc Lua directly. 
Opening this PR to confirm we want to mentioned them like this. 
Preview: https://deploy-preview-1269.quarto.org/license.html

Update version info and links in licences

---

docs/dashboards/_plots-interactive.md

Noticed a typo, 'than' was spelt 'that' and a few missed commas in the tip under the R Graphics heading in this [page](https://quarto.org/docs/dashboards/data-display.html).

Update _plots-interactive.md, edit the tip in R Graphics heading

---

docs/extensions/listings/shortcodes-and-filters.yml

This adds a filter for Typst functions to the filter listing. It is analogous to the `latex-environment` filter, but for Typst. Licensed under MIT, as some code is directly adapted from the `latex-environment` filter.

Update shortcodes-and-filters.yml (Adds typst-function filter)

---

docs/books/book-structure.qmd

Mention that you can use `imakeidx` to build an index (as an alternative to `makeidx`). This package offers a number of additional features.
Provide an example of some of `imakeidx`'s features.
Fix stray "quart" in paragraph.

Mention using imakeidx to build an index

---

docs/output-formats/page-layout.qmd

The word "like" was missing from the sentence on the following example.

Spelling Edit - Missing Word

---

docs/websites/website-search.qmd

The language key for the search box placeholder has been updated from `search-box-placeholder` to `search-text-placeholder`. This ensures that the correct language key is documented.
Fixes quarto-dev/quarto-cli#10485

fix: update language key for search box placeholder

---

docs/journals/templates.qmd
docs/presentations/revealjs/advanced.qmd

This partials is the default one for Quarto using authors and affiliations normalization. This is the one to use as a starter.
Introduced initially in https://github.com/quarto-dev/quarto-cli/commit/9e280991de9cefac47d2088bae4ee620fa752e2a
Closes https://github.com/quarto-dev/quarto-cli/issues/10308
@cwickham asking for review for wording and other style and form comment. 
We can also improved all this when dealing with 
- https://github.com/quarto-dev/quarto-cli/issues/5194

[revealjs] Mention `title-fancy/title-slide.html` as the partial starter to use for the title slide.

---

index.qmd

Hi, there's a typo on the index page in the R section. It's a simple fix, so it should be ready to go.

fix: remove typo from index page

---

docs/projects/scripts.qmd

Found what I assume is a small typo in `docs/projects/scripts.qmd` - at least the previous sentence wasn't really correct 
Sidenote: 
I could not find any specific style guide reg. whitespace in raw markdown-tables, thus I took the freedom to maintain a flush right edge to the table.
~Gw

fix: `docs/projects/scripts.qmd` - fix typo

---

docs/output-formats/page-layout.qmd

Since https://github.com/quarto-dev/quarto-cli/pull/10611 `grid` can be set on a page of a website.
- https://github.com/quarto-dev/quarto-cli/discussions/6615
- https://github.com/quarto-dev/quarto-cli/discussions/10818

docs: grid can be set per page

---

docs/projects/scripts.qmd

We need to document two new environment variables that are necessary to support large projects.

Add documentation for fix in https://github.com/quarto-dev/quarto-cli/issues/10828 

---

docs/authoring/includes.qmd

This pull request adds a tip to the documentation about using absolute paths in the include shortcode. The tip explains that using absolute paths ensures that links and images in included files resolve correctly regardless of where the file is included via the shortcode.
Motivation: several users were bitten by this. The explicit tip might help avoid the issue.

docs: add tip about absolute path in include shortcode important callout

---

docs/download/_download-older.yml
docs/download/index.qmd
tools/release-notes.R

Adds a script to automate the steps of adding release notes for the old release.
Closes https://github.com/quarto-dev/quarto-cli/issues/10277
In addition, we'd need to change this step in the release checklist:
https://github.com/quarto-dev/quarto-cli/blob/a2026c8b7c775665472b73f30b84d8da7a94c178/dev-docs/checklist-make-a-new-quarto-release.md?plain=1#L24
to:
```markdown
- run `quarto run tools/release-notes.R`
```

Script to automate release notes

---

docs/troubleshooting/index.qmd

Adds new quarto check output and a bit of Julia guidance.

add new quarto check output, julia guidance

---

docs/get-started/computations/rstudio.qmd
docs/manuscripts/authoring/_inline-computations.qmd
docs/visual-editor/technical.qmd

The commits in this pull request update the syntax for inline code in the documentation. The changes include using `{r}` primarily instead of `` `r` `` to denote inline R code. These updates improve consistency in the documentation.
Related to quarto-dev/quarto-cli#10805

docs: make bracketed inline code the default syntax

---

docs/websites/website-search.qmd

Document search changes from quarto-cli/pulls/11191

Document search changes from quarto-cli/pulls/11191

---

docs/authoring/variables.qmd

> ([#10936](https://github.com/quarto-dev/quarto-cli/issues/10936)): Use `\\` in `meta` shortcode to escape the following character, allowing keys with `.` in them.

Add note about escaping in meta shortcode

---

docs/publishing/github-pages.qmd
docs/publishing/netlify.qmd
docs/publishing/posit-cloud.qmd
docs/publishing/quarto-pub.qmd
docs/publishing/rstudio-connect.qmd

Replace the usage of actions/setup-python@v4 with actions/setup-python@v5.
Fixes quarto-dev/quarto-cli#11259

docs: Update Python GitHub Action version to v5

---

docs/advanced/typst/typst-css.qmd

A couple more entries in the feature-element matrix checked off, with div supporting `color` and `background-color`.
For quarto-dev/quarto-cli#11280

Typst CSS: update feature-element matrix for div colors

---

docs/presentations/revealjs/index.qmd

Related https://github.com/quarto-dev/quarto-cli/issues/11300
Update documentation to clarify:
- that section title slides are not scrollable by default,
- how to modify them to make them scrollable.

11300 - clarify that section title are not scrollable

---

_quarto.yml
docs/presentations/revealjs/themes.qmd
filters/color-box.lua
styles.css

This is a companion PR to Revealjs callout update to be merged in
- https://github.com/quarto-dev/quarto-cli/pull/11251
It adds documentation for SCSS variable available to customize callouts. 
@cwickham this PR also adds a new feature for our doc: Adding a color box next to some part mentioning a color. 
Basically doing  ``[`<hexcolor>`]{.color-box}`` would use the hexcolor to create the box. It would work with any text using `` [any content]{.color-box color="hexcolor"} `` 
We could probably use that into the website in other places, and we could also make it a shortcode syntax if easier. 
I noticed a few changes in preview locally regarding tables in documentation. I'll check if this is happening with the preview here too. I wonder if our brand change have had side effect

Add documentation for SCSS variables in revealjs

---

docs/blog/posts/_metadata.yml

This should be enough to move discussion from quarto-web to quarto-cli
I created the category there 
https://github.com/quarto-dev/quarto-cli/discussions/categories/blog
I just need to move every post from here to there so that current comments will work. 
I'll try to make a script for that so that we can sync up the merge of this PR with the move. Maybe do it before merging. 
I'll update when done

Move giscus comments to quarto-cli repo discussion board

---

docs/blog/posts/2024-07-02-beautiful-tables-in-typst/index.qmd

tighten iframes in beautiful tables blog post

---

docs/extensions/listings/shortcodes-and-filters.yml

Adds the `typst-math` filter to the filter listing.

Add typst-math to shortcodes-and-filters.ym

---

_variables.yml
docs/faq/rmarkdown.qmd
docs/get-started/authoring/rstudio.qmd
docs/get-started/hello/rstudio.qmd
docs/interactive/shiny/running.qmd
docs/tools/_rstudio.md
docs/visual-editor/index.qmd

closes quarto-dev/quarto-cli#11298
@cwickham do you want to still keep track on version number and update this variable regularly ? 
or should we just say "latest" with a link to https://posit.co/download/rstudio-desktop/ and stop showing the version. 
We don't update our doc at each release on it... 
Otherwise, we could come up with a pre-render script that would query the API at https://posit.co/wp-content/uploads/downloads.json

bump to latest Rstudio IDE version

---

docs/gallery/gallery.yml

- took off `www.` since the url is actually `https://book.utilitr.org/`

Correct link for template

---

docs/authoring/brand.qmd

See https://github.com/quarto-dev/quarto-cli/issues/11604.

Brand documentation should include information about how `brand` interacts with `theme`

---

docs/extensions/listings/shortcodes-and-filters.yml

Update the repository path for the bluesky-comments extension to the correct URL.

fix: incorrect repository name for bluesky-comments extension

---

docs/output-formats/html-lightbox-figures.qmd

See https://github.com/quarto-dev/quarto-cli/blob/83a3b5af86d5f43f5f611009b2af8e74e94ffad3/tests/docs/websites/issue-3686/_extensions/quarto-ext/lightbox/lightbox.lua#L18

to opt out lightbox it should be nolightbox and not no-lightbox

---

docs/authoring/create-citeable-articles.qmd

appendex -> appendix in control options

typo in citable articles

---

_quarto.yml
docs/output-formats/all-formats.qmd

ODF (and its subset ODT) is not tied to one software project. And in any case, Apache OpenOffice is rather on life support, whereas most contributions to the OpenOffice.org descendants are currently going to LibreOffice.
MS Office also opens ODF and recently announced support for version 1.4.

replace "OpenOffice" with "OpenDocument"

---

docs/computations/ojs.qmd

This pull request includes updates to the documentation for using OJS in Quarto documents, specifically in the `docs/computations/ojs.qmd` file. The changes focus on improving the clarity and functionality of the example provided.
Documentation improvements:
* Added an `{ojs}` code cell to read data from a CSV file using `FileAttachment` in the introductory example.
* Updated the description to include a downloadable link to the `palmer-penguins.csv` file and corrected the code cell format to `{{ojs}}` for consistency.

docs: add data import code cell and download link to CSV file

---

docs/extensions/listings/shortcodes-and-filters.yml

mastodon-comments has been renamed to reflect new functionality, so updating repo name and location

renamed extension

---

_quarto.yml
tools/algolia-add-custom-attribute.ts

We're experimenting with fixing our algolia search here.

new custom attribute for algolia search

---

docs/get-started/computations/rstudio.qmd

Currently the link to the full documentation on inline code is "hidden" inside the footnote.
It would be better for it to be clearly visible.
The footnote is mostly there to say the `knitr` syntax is supported.

docs: move link outside of footnote

---

docs/computations/_jupyter-install.md

Related to discussion at https://github.com/quarto-dev/quarto-cli/discussions/11882

Link to virtual environment doc from python install part

---

docs/books/book-basics.qmd

- HTML preview **with** the AsciiDoc ...
- AsciiDoc book to **HTML** ...
- various output forma**ts** ...

docs: Fix grammar and HTML section in book-basics qmd

---

docs/authoring/contents.qmd

The new contents section had some unclear language. So I did some edits for clarity and grammar.

docs: minor edits for clarification of text

---

docs/projects/virtual-environments.qmd

:wave: 
I just found a dead link in the docs. I think that this official conda doc link might be suitable as a replacement.

MINOR: replace dead conda environments link

---

docs/publishing/github-pages.qmd
docs/websites/website-tools.qmd

* Adds a ["Custom Domain"](https://deploy-preview-1583.quarto.org/docs/publishing/github-pages.html#custom-domain) section to Github Pages
* Spells out files Quarto knows to copy to output directory in [Site Resources](https://deploy-preview-1583.quarto.org/docs/websites/website-tools.html#site-resources)
Closes https://github.com/quarto-dev/quarto-cli/issues/4941

Add custom domain set up to Github Pages

---

docs/publishing/github-pages.qmd

Update Custom Domain section: [Preview](https://deploy-preview-1588.quarto.org/docs/publishing/github-pages.html#custom-domain)

Clarify process for custom domains on GitHub Pages

---

docs/computations/julia.qmd
docs/prerelease/1.7/_highlights.qmd
docs/projects/code-execution.qmd

As requested in https://github.com/quarto-dev/quarto-cli/pull/12121#issuecomment-2672641459. Adds some additional docs to the section covering the `julia` engine that highlights some or the main features it currently has.

Expand docs for `julia` engine

---

docs/extensions/listings/shortcodes-and-filters.yml

This filter wraps theorems and proofs in callout blocks for better visual appeal.

Add callouty-theorem to shortcodes-and-filters.yml

---

docs/authoring/_shortcodes.qmd
docs/authoring/version.qmd

Follow-up on the implementation of the "version" shortcode from:
- quarto-dev/quarto-cli#12006
Fixes quarto-dev/quarto-cli#11379

docs: add "version" shortcode

---

docs/authoring/cross-references-custom.qmd

Closes https://github.com/quarto-dev/quarto-cli/issues/11831

Mention `caption-location` on guide page

---

docs/authoring/markdown-basics.qmd

Closes https://github.com/quarto-dev/quarto-cli/issues/12073
Adds an "Other Spans" section: [Preview](https://deploy-preview-1601.quarto.org/docs/authoring/markdown-basics.html#other-spans)

Add special span classes

---

tools/algolia-add-custom-attribute.ts

This will prevent the script to run on incremental render and preview

run post-render script only on project render

---

docs/advanced/typst/typst-css.qmd

It seems the file name was changed.

Update Lua filter which translates CSS properties to Typst link

---

docs/computations/julia.qmd

This pull request includes a small change to the `docs/computations/julia.qmd` file. The change updates the kernel version specified in the document options from `julia-1.7` to `julia-1.8` to make it consistent as it quotes the first example which uses 1.8.

fix: inconsistent kernel version for julia

---

docs/extensions/listings/shortcodes-and-filters.yml

Add [`code-appendix`](https://github.com/cl-roberts/code-appendix) lua filter to extensions page

add code-appedix to shortcodes-and-filters.yml

---

docs/computations/julia.qmd
docs/projects/quarto-projects.qmd

Functionality added in https://github.com/quarto-dev/quarto-cli/pull/11807

Document new `engines` option

---

docs/computations/julia.qmd

By now, the docs for the native engine are nicely fleshed out, however there's still somewhat of a discoverability problem, due to the way that the docs page is structured. Visitors will currently see this table of contents:
The native engine section, while far longer than the rest, is squeezed into one entry at the bottom, appearing like an afterthought. Also, some parts that thematically belong to both engines look like they belong only to the jupyter engine.
In this PR, I've moved the native engine before the Jupyter engine and added a table that clarifies why the native engine should be preferable for most users (this is not to criticize previous efforts, I just think we need to be really clear here as the older engine is still the default, which carries some weight for new users). If …

Refactor Julia page

---

docs/websites/website-navigation.qmd

Hello all, I was reading the redirects doc and felt some additional context could be added to help users better understand why they need to write their config the way they do. I also felt that it would be valuable to have an explicit example for each of the use cases mentioned in the doc, so I added an example for re-organizing directory hierarchy.

Add context and new example to redirects doc

---

docs/advanced/typst/typst-css.qmd

Ref quarto-dev/quarto-cli#12554

Document Typst CSS `font-weight` and `font-style`

---

docs/presentations/beamer.qmd

Documents https://github.com/quarto-dev/quarto-cli/issues/12775

beamer support for layout divs

---

docs/troubleshooting/index.qmd

This pull request enhances the `docs/troubleshooting/index.qmd` file by adding platform-specific instructions for setting the `QUARTO_LOG_LEVEL` environment variable.

fix: use code blocks for copy button

---

docs/troubleshooting/index.qmd

Better not have them just in case, even if both with or without spaces work.

Remove space in powershell command in troubleshooting page

---

docs/computations/julia.qmd
index.qmd

The docs already recommend the `julia` engine over `jupyter` in the julia section, so it makes sense to adjust these copy-paste-able examples to that engine as well so users are put on the right track from the start.

Switch to `engine: julia` in prominent examples

---

docs/advanced/html/external-sources.qmd

Companion PR to revealjs update https://github.com/quarto-dev/quarto-cli/pull/13101
And document missing host we use for mathjax and katex

Add all hosts used for math method

---

docs/extensions/listings/shortcodes-and-filters.yml

This pull request updates the `docs/extensions/listings/shortcodes-and-filters.yml` file by adding several Quarto extensions.
* Added the `badge` extension, which provides a shortcode to display software versions or other information as badges.
* Added the `div-reuse` extension, enabling seamless and efficient content reuse in Quarto.
* Added the `external` extension, allowing inclusion of content or partial content from external files.
* Added the `language-cell-decorator` extension, allowing to automatically add the code block/cell language as header via the `filename` feature.
* Added the `modal` extension for creating Bootstrap modals in HTML documents.
* Added the `preview-colour` extension, which displays a coloured symbol next to colour codes across multiple formats.
* Moved the …

feat: add Quarto extensions

---

docs/extensions/brand.qmd
docs/extensions/creating.qmd

Basic docs for the brand extension released in 1.8.20
I'm owing the users documentation on unified light and dark brand
* https://github.com/quarto-dev/quarto-cli/pull/12883
and the example `brand.yml` uses this feature, so the brand extension page has a callout on this feature as a band-aid.

Brand extension

---

_quarto.yml
theme-dark.scss
theme.scss

This is really minor stuff... Just nuancing the colors controlled by `_quarto.yml`.  More (really minor) hover behavior will come from the light and dark theme files as well
https://github.com/user-attachments/assets/4fe65da5-3568-4c1e-b14f-a11c420ba8b5
https://github.com/user-attachments/assets/fd0da527-4a32-4935-8a51-e34fd5a0ec6c
https://github.com/user-attachments/assets/7111231e-036f-4e12-88b9-839a8dd1d271
https://github.com/user-attachments/assets/e2ff1d85-41ba-4ec6-9cf1-f1181bbe9135

Slight "supported by Posit" badge color tweaks

---

docs/extensions/listings/revealjs.yml

Allows drawing and erasing in a revealjs presentation rendered via quarto.
The demo can be watched [here](https://www.thinkermahmud.com/qdraw/#/video-demo)

Add qdraw extension to revealjs.yml

---

docs/authoring/brand.qmd

Say a little bit more about `quarto use brand` on the prerelease site, and "watch this page".

`quarto use brand` teaser

---

docs/extensions/lua-api.qmd

In HTML dependencies section, the description of `link` has a typo where `ref` is written instead of `href`.

fix: typo `ref` instead of `href`
