quarto-dev/quarto-web

docs/websites/website-basics.md
=> minor typo fix 2

docs/getting-started/quarto-basics.qmd
=> fix broken link

docs/projects/virtual-environments.qmd
=> fix typo in link

docs/websites/website-navigation.qmd
- State how breaking the navigation looks like in the sidebar
- Add missing period at the end of the sentence
=> Clarify behaviour and add missing period

docs/presentations/revealjs/advanced.qmd
Since there is no section called Incremental Content
=> Fix link to point to #incremental-lists

docs/authoring/tables.qmd
Just a few typo fixes + minor edits.
=> Typos + minor edits

docs/tools/rstudio.qmd
=> Correct typo

docs/authoring/title-blocks.qmd
A couple of small edits I noticed as I was reading through!
=> Edit small typos

docs/presentations/revealjs/index.qmd
If you have not already seen it. 
Modified on mobile so I did not rebuild anything.
=> Probably duplicated backtick

docs/presentations/revealjs/index.qmd
Or add long footnote if prefered syntax
Part of reports from https://github.com/quarto-dev/quarto-cli/issues/459
=> Use inline foonotes syntax in revealjs example

docs/authoring/cross-references.qmd
* use raw text instead of image
=> * update Equations section in cross-references.qmd

docs/reference/dates.qmd
Following addition in https://github.com/quarto-dev/quarto-cli/pull/576
cc @dragonstyle
=> Add `iso` alias in valid Date Style

docs/faq/index.qmd
Is it worth mentioning here, or would it be confusing (both knitr and jupyter support multiple languages, and users may naturally ask how to choose between which engine to use if they want to use multiple languages in the same doc)?
=> Mention that knitr also supports languages besides R

docs/websites/website-listings.qmd
listing not listings (I assume)
=> Typo in example

docs/projects/quarto-projects.qmd
A small pull request to let people know about the suggestion by @jjallaire in https://github.com/quarto-dev/quarto-cli/issues/802 
(see https://github.com/quarto-dev/quarto-cli/issues/802#issuecomment-1118687990) regarding `_index.md`
=> Suggestion for _index.md files

docs/output-formats/all-formats.qmd
Fix typo, spelling and punctuation
=> Minor tweaks

docs/projects/quarto-projects.qmd
This feature had not been documented yet.
=> Mention metadata-files in project basics

docs/websites/website-blog.qmd
* Remove extra https:// at the beginning of example RSS URL
=> Fix dummy RSS url

docs/websites/website-listings.qmd
Small typo on listing contents
=> fix typo: listing contents

docs/reference/projects/_websites.md
* Best practice is to make the examples in the documentation as accessible as possible, since people follow them as a model.
=> Use `aria-label` in Nav Items example

docs/output-formats/html-basics.qmd
=> fix a typo in html-basics.qmd

docs/get-started/hello/rstudio.qmd
fix typo in version number for RStudio download
=> update version number of RStudio download

docs/projects/virtual-environments.qmd
=> fix typo in virtual-environments.qmd

docs/publishing/netlify.qmd
The target was **hard coded** at two places to **gh-pages** instead of netlify
=> Update target to netlify

docs/faq/rmarkdown.qmd
This PR modifies some of the answer regarding custom formats equivalent in Quarto, and V1.0 announcement at the conf.
=> Update some question following v1.0 announcement

docs/presentations/revealjs/presenting.qmd
The current phrasing is a bit confusing, and seems to suggest the contrary of what one would expect. That is, unless I am misunderstanding something.
=> Adjust phrasing to note

docs/publishing/ci.qmd
as it's not part of the command, but of the sentence where the command is mentioned
=> move closing parenthesis out of CLI code snippet

docs/extensions/formats.qmd
=> fix bug: `----` -> `---`

docs/authoring/article-layout.qmd, docs/blog/posts/2022-02-17-advanced-layout/index.qmd, docs/computations/execution-options.qmd, docs/computations/r.qmd, docs/output-formats/html-code.qmd, docs/presentations/revealjs/demo/index.qmd, docs/tools/_chunk-options.md
While reading through https://quarto.org/docs/computations/r.html I noticed a few style inconsistencies in how ggplot command were formatted.
=> Make style of ggplot commands consistent

docs/websites/website-about.qmd
change .png to .jpg to match example file endings
fix Sept typo + make all Sept/Sep usage consistent
=> Fix minor typos

docs/authoring/callouts.qmd
remove the `;` which is not part of YAML syntax
=> typo in doc regarding YAML syntax

docs/authoring/title-blocks.qmd, docs/journals/authors.qmd, docs/tools/jupyter-lab.qmd, docs/tools/vscode.qmd
Just a bunch of typos, and a rewording of one awkward phrase.
=> Fix various typos

docs/websites/website-listings.qmd
Related to this discussion https://github.com/quarto-dev/quarto-cli/discussions/2831#discussion-4470231
=> a note on the constraints to appear in the list

docs/websites/website-tools.qmd
see https://github.com/quarto-dev/quarto-cli/issues/2797
It would still need more documentation, margin-footer seem to work only if there is a navbar, I did not succeed in making  `body-footer/header` to work. A minimal viable example of a `_quarto.yml` would help
=> add some notes on fig links

docs/extensions/listings/shortcodes-and-filters.yml
I have added an entry for a shortcode extension 'bsicons' in the shortcodes-and-filters yml file and changed the last part of the description a  bit of my recently added filter extension 'collapse-callout`.
=> added an entry for a shortcode extension 'bsicons' in the shortcodes-and-filters yml file

docs/websites/website-listings.qmd
This hopefully will save other people time, if you're dealing with complex websites!
=> add clarification for relative file locations

docs/extensions/listings/shortcodes-and-filters.yml
It's to create forms!  Why do you need forms in static sites?  Don't ask!
=> add my extension

docs/authoring/markdown-basics.qmd
Nice to know which languages are actually supported and where to propose additions.
=> Add link to a list of supported syntax highlighting languages

bug-reports.qmd
This is adding as example how to set `QUARTO_PRINT_STACK` on Windows for helping debug
=> Add command for setting env var on windows powershell

docs/extensions/listings/revealjs.yml
I have just created this extension. I would like to add it to the list of quarto extensions. 
Thanks :)
=> Add confetti extension

docs/publishing/github-pages.qmd
=> remove caution for Windows

docs/extensions/filters.qmd
Thanks for the fantastic quarto tool!
=> Fix minor typo in filters.qmd

docs/computations/execution-options.qmd
Inspired by this https://github.com/quarto-dev/quarto-cli/discussions/3700#discussioncomment-4439358
=> Useful not about Bash and Python coexistence

docs/authoring/cross-references.qmd
Just noticed that "subtables" on line 183 was missing the first "b", so I added it.
=> Fixed one typo

docs/extensions/lua-api.qmd
Fixed a minor typo in docs/extensions/lua-api.md.
=> Fixed typo in docs/extensions/lua-api.md

docs/extensions/listings/shortcodes-and-filters.yml
[`downloadthis`](https://github.com/shafayetShafee/downloadthis) provides shortcode for implementing download buttons in html output file.
=> Added an entry for shortcode in shortcode-and-filter listing

docs/extensions/listings/shortcodes-and-filters.yml
Add Quarto Pseudocode Extension
=> Add Quarto Pseudocode Extension

docs/prerelease/1.3/_pre-release-feature.qmd, docs/prerelease/1.3/asciidoc-books.qmd, docs/prerelease/1.3/ast.qmd, docs/prerelease/1.3/code-annotation.qmd, docs/prerelease/1.3/embed.qmd, docs/prerelease/1.3/grid.qmd, docs/prerelease/1.3/kbd.qmd, docs/prerelease/1.3/mermaid.qmd, docs/prerelease/1.3/multi-format.qmd, docs/prerelease/1.3/pdf.qmd, docs/prerelease/1.3/tables.qmd
Add callout to alert people that land on a highlight page that the feature described requires the pre-release.
=> Add pre-release callout highlights pages 

docs/prerelease/1.3/code-annotation.qmd
Remove figure that was no longer necessary.
=> Fix to code annotation docs

docs/extensions/listings/shortcodes-and-filters.yml
I have made a Quarto shortcode [`material-icons`](https://github.com/shafayetShafee/material-icons) and added that to the shortcode listings.
=> added an entry for material-icons in shortcodes-and-filters.yml

docs/prerelease/1.3/_highlights.qmd, docs/prerelease/1.3/confluence.qmd
#closes https://github.com/rstudio/quarto-confluence-test/issues/73
=> [Confluence] Pre release docs

_quarto.yml
#closes https://github.com/rstudio/quarto-confluence-test/issues/73
=> Confluence Pre Release - add to listing

docs/authoring/callouts.qmd, docs/prerelease/1.3/custom-ast-nodes/callout.qmd
This doc PR accompanies https://github.com/quarto-dev/quarto-cli/pull/4449.
=> Callout caption -> title

docs/prerelease/1.3/multi-format.qmd
Changes:
* Reorder and minor rewording
* Add note to get all formats rendered in RStudio and VS Code.
Fixes quarto-dev/quarto-cli#4453
=> Multi-format docs

docs/extensions/listings/shortcodes-and-filters.yml
Used in production for the journal Dialectica, sample: https://dialectica.philosophie.ch/dialectica/article/view/12
=> Extension list: add first-line-indent filter

docs/authoring/figures.qmd
As a first time user reviewing the documentation and working with this kind of language, I had to experiment to find out how to apply multiple formatting specifications. I thought it was worth including in the documentation.
First time I do this kind of thing so please double check I didn't break anything else as I scrolled all over the page copying and pasting!
=> Add how to specify multiple Figure params

docs/get-started/hello/vscode.qmd
=> Fixed a minor typo

docs/blog/posts/2023-03-17-jupyter-cell-embedding/index.qmd, docs/blog/posts/2023-03-20-confluence/index.qmd
=> Make minor edits to copy for 1.3 release blog posts.

docs/extensions/listings/shortcodes-and-filters.yml
Created a filter [`black-formatter`](https://github.com/shafayetShafee/black-formatter) to format python codes in the python code chunk with black code formatter.
=> Added an entry for filter in the shortcodes-and-filters.yml file

docs/get-started/computations/rstudio.qmd
Please bear with me, I am still learning Git&GitHub. I don't know if it's good practice to create such a pull request for only 2 typos, but I wanted to give it a try. Thank you!
=> Correction of 2 Typos

docs/authoring/language.qmd
Please freely use my suggested edit
=> Double verb/typo

docs/extensions/lua.qmd
Add alt text for VS Code screenshots on Lua Development page.
=> Add alt text for Lua in VS Code.

docs/authoring/notebook-embed.qmd
Fixes https://github.com/quarto-dev/quarto-cli/issues/5372
=> Fix broken link to notebook

docs/prerelease/1.4/_pre-release-feature.qmd, docs/prerelease/1.4/lua_changes.qmd, docs/prerelease/1.4/typst.qmd
Companion PR to https://github.com/quarto-dev/quarto-cli/pull/5575
=> Add information about bibliography processing for typst format

docs/extensions/listings/revealjs-formats.yml
Live demo here: https://grantmcdermott.com/quarto-revealjs-clean-demo/template.html
=> Add clean reveal.js theme

docs/authoring/diagrams.qmd
see https://github.com/quarto-dev/quarto-cli/issues/5767
=> Note requirement for cell options

docs/reference/dates.qmd
Add precision for `date: last-modified` to be more precise that it concerns the input file date
=> `last-modified` is about the input file date and time

docs/extensions/shortcodes.qmd
Fix typo and other small tweaks.
=> Tweak shortcodes.qmd

docs/manuscripts/authoring/_overview.qmd
Further emphasize that `.qmd` will be converted to `.ipynb` (and benefits thereof)
=> minor tweak to rstudio notebook language

docs/manuscripts/authoring/_setup.qmd, docs/manuscripts/authoring/_workflow-qmd.qmd
* Try to emphasize need for all branches for template clone
* Add `jupyter` to Python requirements in VS Code (also added `requirements.txt` to relevant template repo)
* Edit workflow to reflect the default will be to not automatically re-render on save
=> Manuscript fixes

docs/authoring/figures.qmd, docs/authoring/markdown-basics.qmd
Closes https://github.com/quarto-dev/quarto-cli/issues/4600
Preview Changes:
* [Lists](https://deploy-preview-781--mystifying-jepsen-fa4396.netlify.app/docs/authoring/markdown-basics.html#lists)
* [Block Layout](https://deploy-preview-781--mystifying-jepsen-fa4396.netlify.app/docs/authoring/figures.html#block-layout)
=> Add examples of using divs to separate content

docs/authoring/front-matter.qmd, docs/journals/authors.qmd
Fixes problems reported under Remarks in: https://github.com/quarto-dev/quarto-cli/discussions/5860#discussioncomment-6290755
=> Front matter fixes

docs/projects/quarto-projects.qmd
Closes https://github.com/quarto-dev/quarto-cli/issues/4518
=> Add comment about format metadata merging

docs/publishing/confluence.qmd
Closes https://github.com/quarto-dev/quarto-cli/issues/5243
=> Clarify confluence publishing is cloud only

docs/computations/_jupyter-rendering.md, docs/computations/r.qmd
Closes https://github.com/quarto-dev/quarto-cli/issues/4462
=> Clarify `render` renders all formats

_variables.yml
Updating the latest RStudio release version.
=> Update _variables.yml latest RStudio version

docs/authoring/footnotes-and-citations.qmd
Added the specific cls style used to produce the examples
=> Added citation style info in the example table

docs/authoring/create-citeable-articles.qmd
Texts in affiliation and affiliation-url shall be consistent
=> Fix typo in create-citeable-articles.qmd

docs/prerelease/1.4/typst.qmd
The entry was repeated, this removes one of them
=> Remove repeated "poster" on typst page

docs/gallery/gallery.yml
Adds R4PDE book made with Quarto
=> Adds example to gallery.yml

docs/interactive/shiny/execution.qmd
=> Typo in execution.qmd

index.qmd
yihui uses knitr at all times, so I think the original author should be respected.
=> Change "Knitr" to "knitr" in the index.qmd file

docs/extensions/listings/shortcodes-and-filters.yml
- https://github.com/kdheepak/quarto-svgbob
- demo: http://kdheepak.com/quarto-svgbob/
=> feat: Add svgbob extension

docs/dashboards/interactivity/shiny-python/_shiny-advanced.md, docs/dashboards/interactivity/shiny-python/_shiny-requirements.qmd, docs/dashboards/interactivity/shiny-python/_shiny-sidebar.md, docs/dashboards/interactivity/shiny-python/index.qmd
Replaces #905. Created a new PR so that it would automatically deploy previews on push.
=> Shiny tutorial

docs/extensions/distributing.qmd
Provides examples of valid semantic versioning
=> Improve details behind specifying a development `version`

docs/presentations/revealjs/advanced.qmd
Added in quarto-dev/quarto-cli#7946 for 1.4
=> Add doc about nostrech class on image

docs/prerelease/1.4/_highlights.qmd
Adds item here: https://deploy-preview-973--mystifying-jepsen-fa4396.netlify.app/docs/prerelease/1.4/
=> Add `rem-` and `sol-` to Cross Ref Highlights

docs/books/book-output.qmd, docs/output-formats/ms-word-templates.qmd
closes https://github.com/quarto-dev/quarto-cli/issues/4502
=> Add a part about custom style in markdown for DOCX reference doc

docs/authoring/includes.qmd
and add details for including computations
closes https://github.com/quarto-dev/quarto-cli/issues/8305
=> Add example about using include shortcode within source code block

docs/projects/scripts.qmd
Updates new location of yaml lib.
See [#8521](https://github.com/quarto-dev/quarto-cli/discussions/8521#discussioncomment-8326282) on quarto-cli discussion.
=> Update link to deno yaml lib

trademark.qmd
Confirmed with Kim B. that this alias does exist for Posit, so changing to keep branding consistent
=> Update email from rstudio to posit

docs/publishing/github-pages.qmd
Do the files rendered to `docs/` need adding and committing before they can be pushed?
=> Add missing `git add` and `git commit` commands

docs/extensions/listings/shortcodes-and-filters.yml
=> add watermark filter

docs/authoring/callouts.qmd
this should orientate people like me seachinf for this functionality
=> note on collapse option

docs/presentations/index.qmd
=> Minor grammatical edits

docs/extensions/listings/shortcodes-and-filters.yml
=> add style-text filter

docs/extensions/listings/shortcodes-and-filters.yml
Adds the `share-post` shortcode extensions
=> Add `share-post`

docs/authoring/create-citeable-articles.qmd
Some of this page spelled it like the musician, while some didn't.  I made it consistently like the musician
https://en.wikipedia.org/wiki/Norah_Jones
=> consistently "Norah"

_quarto.yml, docs/advanced/jupyter/kernel-execution.qmd
To be merged when https://github.com/quarto-dev/quarto-cli/pull/9130 lands.
=> advanced docs: 1.5 kernel execution configuration

docs/extensions/listings/custom-formats.yml
A publication quality PDF format for academic papers.
[GitHub repo](https://github.com/AaronGullickson/aog-article-quarto)
[Preview of template](https://aarongullickson.quarto.pub/demo-of-aog-article-template/)
=> Add aog-article

docs/prerelease/1.5/_highlights.qmd, docs/prerelease/1.5/pre-render.qmd
Update 1.5 Highlights format [Preview](https://deploy-preview-1060--mystifying-jepsen-fa4396.netlify.app/docs/prerelease/1.5/)
=> Update 1.5 highlights to follow format of previous highlights

index.qmd
This pull request fixes the issue where an image with a fixed height leads to bad display. The changes include updating the `index.qmd` file to remove the fixed height attribute for the image and setting a `max-height` instead.
=> fix: image display issue on mobile

docs/websites/website-navigation.qmd
Closes https://github.com/quarto-dev/quarto-cli/issues/5688
=> Add `target` to nav item options

docs/computations/julia.qmd, docs/prerelease/1.5/_highlights.qmd
* Add pre-release callout to docs
* Add to Julia engine to 1.5 highlights
=> Julia engine doc edits

docs/computations/julia.qmd
Describes usage of `QUARTO_JULIA_PROJECT` added in https://github.com/quarto-dev/quarto-cli/pull/9373
(Edit from @cwickham): [Preview](https://deploy-preview-1078--mystifying-jepsen-fa4396.netlify.app/docs/computations/julia.html#installation-1)
=> Docs for PR 9373

docs/output-formats/pdf-basics.qmd
Add 'of' in the first sentence.
=> Add a grammer correction

docs/extensions/listings/revealjs-formats.yml
Adds link to University of Arizona inspired revealjs theme extension
=> Add uaz-revealjs to revealjs-formats.yml

.github/workflows/preview.yml, .github/workflows/publish.yml, _quarto-prerelease-docs.yml, theme-prerelease-docs.scss
Attempt at adding a banner for pre-release docs site.
Uses a profile, so to see result use:
```
quarto preview --profile prerelease-docs
```
=> Pre-release Banner

docs/extensions/listings/revealjs.yml
Adds link to flashcards quarto extension
=> Add flashcards Quarto extension to listing

docs/output-formats/html-themes.qmd
"the website" -> "this website"
=> fix typo html-themes.qmd

docs/websites/website-basics.qmd
Closes https://github.com/quarto-dev/quarto-cli/issues/9488
=> Add website theme section to basics

_quarto.yml, docs/extensions/creating.qmd, docs/extensions/metadata.qmd
To be merged after https://github.com/quarto-dev/quarto-cli/pull/9953 is merged.
=> metadata extensions

docs/authoring/variables.qmd
Closes https://github.com/quarto-dev/quarto-cli/issues/8307
=> Add indexing example to meta shortcode

docs/authoring/code-annotation.qmd, docs/output-formats/_theme-variables.md
Closes https://github.com/quarto-dev/quarto-cli/issues/4966
=> Add code annotation SASS variables

docs/extensions/listings/journal-articles.yml
Add Quarto template for MDPI journals
=> Quarto template for MDPI journals

docs/output-formats/pdf-basics.qmd
Correct the grammar used in Unicode Characters.
=> Add a grammar correction

docs/presentations/_columns.md, docs/presentations/powerpoint.qmd
Fixes quarto-dev/quarto-cli#2635
=> docs: add a note about `width` (in column) being not supported in `pptx`

docs/websites/website-listings.qmd
Closes https://github.com/quarto-dev/quarto-cli/issues/5858
=> Add example of passing options to `feed`

docs/advanced/inspect/index.qmd, docs/advanced/inspect/quarto-inspect-document-json-schema.json, docs/advanced/inspect/quarto-inspect-project-json-schema.json
=> `quarto inspect` docs

docs/authoring/citations.qmd, docs/output-formats/_typst-citations.md, docs/output-formats/typst.qmd
[Preview](https://deploy-preview-1209.quarto.org/docs/authoring/citations.html)
Closes https://github.com/quarto-dev/quarto-cli/issues/9762
=> Add Typst details to main citation page

docs/computations/julia.qmd
Cf. https://github.com/quarto-dev/quarto-cli/discussions/9712
=> Clarify role of environments in julia engine docs

docs/extensions/shortcodes.qmd, docs/prerelease/1.5/_highlights.qmd
In 1.5, Shortcode handlers can respond to the context in which they were called.
=> document shortcode context

docs/extensions/listings/shortcodes-and-filters.yml
Adds a few extensions I've created in the last month-ish.
* [auto-dark](https://pkg.garrickadenbuie.com/quarto-auto-dark)
* [tachyons](https://pkg.garrickadenbuie.com/quarto-tachyons)
* [base64](https://pkg.garrickadenbuie.com/quarto-base64)
* [partials](https://pkg.garrickadenbuie.com/quarto-partials)
=> Add quarto extensions by @gadenbuie

docs/blog/posts/2024-07-02-beautiful-tables-in-typst/examples/gt-cars.qmd
Avoid gt deprecated arguments.
=> Avoid gt deprecated arguments

docs/presentations/revealjs/advanced.qmd
closes https://github.com/quarto-dev/quarto-cli/issues/10022
=> revealjs - add `center-title-slide` documentation

docs/extensions/formats.qmd
Fix a tiny Typo.
Thanks for everything you're doing!
=> [Tiny PR] Fix a typo

docs/authoring/front-matter.qmd
This is companion PR to https://github.com/quarto-dev/quarto-cli/pull/10763
To be merged after it. 
Note: All the reformatting happened because I used visual mode to edit the table.
=> Add support for CC0 licence

_quarto.yml
This fixes the broken logo image we saw on our weekly meeting.
=> fix bad logo image

docs/websites/website-listings-custom.qmd
This should be `to write` not `write`.
=> docs: fixes grammar issue by adding `to`

docs/extensions/listings/revealjs.yml
Hello, I've created this extension in the hope that it will be useful ✌️
=> add quarto i18n extension

docs/websites/website-blog.qmd
=> MINOR: fix typo

docs/computations/julia.qmd
"interupt" changed to "interrupt"
=> Fixed spelling error

docs/blog/posts/2024-10-15-conf-workshops-materials/index.qmd
("UC Berkeley", not "Berkeley University")
=> fix university name

docs/manuscripts/authoring/_inline-computations.qmd
Closes https://github.com/quarto-dev/quarto-cli/issues/7939
=> Update RStudio and VS Code manuscript tutorials to use inline code syntax

docs/authoring/variables.qmd
Closes https://github.com/quarto-dev/quarto-cli/issues/4624
=> Clarify what kind of markdown is allowed in `_variables.yml`

docs/authoring/markdown-basics.qmd
Closes https://github.com/quarto-dev/quarto-cli/issues/7894
=> Add callout for unique footnote IDs

_quarto.yml
Flip profiles so we start showing 1.6 RC downloads by default.
=> flip to rc mode

docs/extensions/listings/custom-formats.yml
Custom Format for the easy creation of slides using typst and the diatypst package. Similiar to beamer slides in quarto, but faster
=> add the diaquarto extension

docs/extensions/listings/custom-formats.yml
A Quarto extension for generating PDF letters using Typst or LaTeX
=> quarto-letter

docs/faq/index.qmd
Some updates given our forum discussions.
=> refresh faq

tools/release-notes.R
* Use `-` in dates
* Fix prerelease version in message to console
=> Fixes to release note script

docs/extensions/listings/shortcodes-and-filters.yml
https://pkg.garrickadenbuie.com/quarto-bluesky-comments/
=> Add gadenbuie/quarto-bluesky-comments

docs/extensions/lua-api.qmd
and reformat using Visual Mode
=> Add `quarto.paths.tinytex_bin_dir()`

docs/faq/index.qmd
=> docs: Fix article in faq index qmd

docs/websites/website-tools.qmd
Fixes quarto-dev/quarto-cli#12221
=> fix: typo "xslx" to "xlsx"

docs/output-formats/html-lightbox-figures.qmd
Fixes quarto-dev/quarto-cli#12410
=> fix(html-lightbox-figures.qmd): typo

docs/computations/r.qmd
Fixes quarto-dev/quarto-cli#12411
=> fix(emacs): typo

docs/extensions/lua-api.qmd, docs/extensions/shortcodes.qmd
Docs for https://github.com/quarto-dev/quarto-cli/pull/12421
=> Lua: `quarto.shortcode.*`

docs/manuscripts/components.qmd
Closes https://github.com/quarto-dev/quarto-cli/issues/11917
=> Add code-links examples

docs/manuscripts/components.qmd
To address comment: https://github.com/quarto-dev/quarto-cli/issues/11917#issuecomment-2771773980
=> Clarify requirements for code-links: repo

docs/authoring/_format-aliases.md
Companion PR to quarto-dev/quarto-cli#12462
=> Add new supported alias for `when-format` and `unless-format`

docs/presentations/revealjs/themes.qmd
This closes https://github.com/quarto-dev/quarto-cli/issues/12708
=> fix color variable values (thanks @EllaKaye!)

docs/authoring/markdown-basics.qmd
Ensure proper indentation for lists by correcting the first character alignment.
Also add an example with a code block inside a list.
=> docs(markdown-basics.qmd): use proper list indentation (stricter syntax)

docs/authoring/cross-references-divs.qmd
See https://github.com/quarto-dev/quarto-cli/issues/13019#issuecomment-3024734621
=> Warn about block-level equations and div syntax.

docs/authoring/_kbd.qmd
Provide explicit descriptions of the features.
=> improve kbd docs

_quarto.yml
https://posit-dev.github.io/supported-by-posit/
=> Add standard supported banner

docs/extensions/listings/shortcodes-and-filters.yml
Added output-styling extension details to the YAML file.
=> Add quarto-output-styling extension information
